'use strict';
/**
 * sweep_golden.gen.js — regenerates the MC_GOLDEN block inside sweep_golden.js.
 *
 *   node sweep_golden.gen.js
 *
 * Rewrites only the region between the GENERATED markers, in place. Run it when
 * buildVariations() is DELIBERATELY changed, then read the diff: every line of it is a behavior
 * change you are asserting is intended. Never run it to make a failing test pass.
 *
 * The Optimizer half of the golden (OPT_GOLDEN) cannot be generated here — its enumeration lives
 * inside `_runOptimizerNow()` in optimizer_ui.js and needs a live `getInputs()` base and the real
 * NERD_KNOBS flag. See OPT_GOLDEN's note in sweep_golden.js for the browser capture.
 */

const fs = require('fs');
const path = require('path');

globalThis.performance = { now: () => 0 };
globalThis.window = {};
globalThis.document = { getElementById: () => null, addEventListener: () => {} };

const here = __dirname;
Object.assign(globalThis, require(path.join(here, 'taxengine.js')));
const core = require(path.join(here, 'optimizer_core.js'));
const { SWEEP_BASES } = require(path.join(here, 'sweep_golden.js'));

// The fields that actually SELECT an arm. Everything else on a variation row is inherited from
// the base object, so recording it would pin the fixture rather than the enumeration.
const SEL_KEYS = ['strategy', 'propWithdraw', 'nYears', 'stratRate', 'stratIRMAATier',
                  'stratACAMultiple', 'iraWithdrawPct', 'orderedSeq', 'gkGuard', 'gkAdjPct',
                  'cyclicEnabled', 'cyclicOrder', 'fundConversionWithCash',
                  'convertExcessToRoth', 'extraConversionAmount'];

function selectionOf(v) {
    const o = {};
    for (const k of SEL_KEYS) if (v[k] !== undefined) o[k] = v[k];
    return o;
}

const golden = {};
for (const [name, base] of Object.entries(SWEEP_BASES)) {
    const rows = core.buildVariations(base);
    const baseRows = rows.filter(r => !r.cyclicEnabled && !r.fundConversionWithCash);
    golden[name] = {
        rowCount: rows.length,
        baseRowCount: baseRows.length,
        labels: rows.map(r => r._label),
        baseRows: baseRows.map(r => [r._strategyFamily, r._paramLabel, r._paramSortVal, selectionOf(r)]),
    };
}

const START = '// >>> MC_GOLDEN GENERATED by sweep_golden.gen.js — do not hand-edit';
const END   = '// <<< MC_GOLDEN GENERATED';

const file = path.join(here, 'sweep_golden.js');
const src  = fs.readFileSync(file, 'utf8');
const i = src.indexOf(START), j = src.indexOf(END);
if (i < 0 || j < 0 || j < i) {
    console.error('sweep_golden.js: GENERATED markers not found — refusing to write.');
    process.exit(1);
}

// Hand-rolled formatter rather than JSON.stringify(_, null, 4): one label per line and one
// baseRow per line keeps the diff of a deliberate change readable. Fully expanded, the selection
// objects alone push the block past 2,700 lines and every real change hides in the noise.
function fmt(g) {
    const q = s => JSON.stringify(s);
    const parts = Object.entries(g).map(([name, e]) => [
        `    ${q(name)}: {`,
        `        rowCount: ${e.rowCount},`,
        `        baseRowCount: ${e.baseRowCount},`,
        `        labels: [`,
        ...e.labels.map(l => `            ${q(l)},`),
        `        ],`,
        `        baseRows: [`,
        ...e.baseRows.map(r => `            [${q(r[0])}, ${q(r[1])}, ${JSON.stringify(r[2])}, ${JSON.stringify(r[3])}],`),
        `        ],`,
        `    },`,
    ].join('\n'));
    return `{\n${parts.join('\n')}\n}`;
}

const block = `${START}\nconst MC_GOLDEN = ${fmt(golden)};\n`;
fs.writeFileSync(file, src.slice(0, i) + block + src.slice(j), 'utf8');

const total = Object.values(golden).reduce((n, g) => n + g.rowCount, 0);
console.log(`sweep_golden.js MC_GOLDEN rewritten: ${Object.keys(golden).length} bases, ${total} rows recorded.`);
for (const [k, g] of Object.entries(golden)) console.log(`  ${k}: ${g.rowCount} rows (${g.baseRowCount} base)`);
